### ISSUE TITLE
Unexpected token var...UnityLoader[r] is not a function

### ISSUE THREAD

**Issue by AiPrizrak** [kmturley/angular-unity#1]
I'm trying to use your example project to add my webgl build, and get an error:
Uncaught SyntaxError: Unexpected token var
ERROR TypeError: UnityLoader[r] is not a function
    at UnityLoader.loadCode.Module (UnityLoader.js:4)
    at HTMLScriptElement.o.onload [as __zone_symbol__ON_PROPERTYload] (UnityLoader.js:4)
    at HTMLScriptElement.wrapFn (zone.js:1188)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3811)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:420)
    at Zone.push../node_modules/zone.js/dist/zone.js.Zone.runTask (zone.js:188)
    at ZoneTask.push../node_modules/zone.js/dist/zone.js.ZoneTask.invokeTask [as invoke] (zone.js:496)
    at invokeTask (zone.js:1540)
    at HTMLScriptElement.globalZoneAwareCallback (zone.js:1566)

I think it has some issues with newest webgl bundler, can you tell which version was used here?
If you have any suggestions how to make it work, I'm open to hear.

**Comment by AiPrizrak** [comment]
The issue has been solved, I suppose it's webgl bundler who's making the mess here. Tried unity 18.4 and it worked well. Also successfully updated to angular 8.2.2 without any issues.

**Comment by kmturley** [comment]
Great, so are there any changes needed in my example project?

**Comment by AiPrizrak** [comment]
No, don't think so, unless you have some pocket miracle to get make it work with webgl 19.2.0

**Comment by kmturley** [comment]
I don't have the latest version so unable to try right now. but will test later!

**Comment by Silencexuandream** [comment]
Has the problem been solved

**Comment by kmturley** [comment]
Have upgraded to Angular 12, Unity 2020 is a little more tricky.

2020 version requires an additional .jslib script, see guide here:
https://docs.unity3d.com/Manual/webgl-interactingwithbrowserscripting.html
